# Generated by Django 2.0.6 on 2018-06-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppingcart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Buy'),
        ),
        migrations.AddField(
            model_name='send',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
