# Generated by Django 2.0.6 on 2018-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribute', '0002_auto_20180624_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
