# Generated by Django 2.0.6 on 2018-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productavailable',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productavailable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productavailable',
            name='sede',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductAvailable',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
