# Generated by Django 2.0.6 on 2018-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img-default/productdefault.jpg', upload_to='photoproduct/%Y/%m/%d/'),
        ),
    ]
