# Generated by Django 2.0.6 on 2018-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180624_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
