# Generated by Django 2.0.6 on 2018-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180625_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
